'use strict';
var SPORTS={badminton:['🏸','Badminton',['Simple','Double'],11],basketball:['🏀','Basket-ball',['3 contre 3','5 contre 5'],11],handball:['🤾','Handball',['4 contre 4','7 contre 7'],5],football:['⚽','Football',['5 contre 5','8 contre 8','11 contre 11','Futsal'],3],volleyball:['🏐','Volley-ball',['2 contre 2','4 contre 4','6 contre 6'],15],tabletennis:['🏓','Tennis de table',['Simple','Double'],11],tennis:['🎾','Tennis',['Simple','Double'],4],ultimate:['🥏','Ultimate',['5 contre 5'],7],rugby:['🏉','Rugby',['5 contre 5','7 contre 7'],5],hockey:['🏑','Hockey',['5 contre 5'],5],custom:['🏅','Autre activité',['Format libre'],10]};
var COLORS=['#2563eb','#ef4444','#16a34a','#eab308','#7c3aed','#ea580c','#0891b2','#db2777','#334155','#84cc16','#0d9488','#8b5cf6'];
var FORMULAS={roundrobin:['Championnat','Tout le monde rencontre tout le monde.'],pools:['Poules + finales','Deux poules puis demi-finales et finales.'],knockout:['Élimination directe','Le vainqueur avance dans le tableau.'],ladder:['Montante-descendante','Le vainqueur monte, le perdant descend.'],swiss:['Ronde suisse','Les équipes proches au classement se rencontrent.']};
var MODES={time:['Au temps','Le buzzer arrête le match.'],score:['Au score','Le premier au score cible gagne.'],hybrid:['Score ou temps','La première condition atteinte termine le match.'],free:['Libre','Le match est terminé manuellement.']};
var KEY='tournoi-eps-v3',audio=null,timer=null;
var $=function(s){return document.querySelector(s)}, $$=function(s){return Array.from(document.querySelectorAll(s))};
function teams(n,old){old=old||[];var a=[];for(var i=0;i<n;i++)a.push(old[i]||{id:'t'+(i+1),name:'Équipe '+(i+1),color:COLORS[i%COLORS.length],members:[]});return a.map(function(t,i){t.id='t'+(i+1);return t});}
function draft(){return{name:'Tournoi EPS',sport:'badminton',format:'Simple',courts:4,count:8,teams:teams(8),formula:'roundrobin',mode:'time',duration:300,target:11,strategy:'independent',studentStart:true,studentScore:true,sound:true}}
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'null')||{screen:'home',step:1,draft:draft(),role:'teacher'}}catch(e){return{screen:'home',step:1,draft:draft(),role:'teacher'}}}
var state=load();
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}}
function esc(s){return String(s==null?'':s).replace(/[&<>"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]})}
function show(id){['homeView','wizardView','tournamentView'].forEach(function(x){$('#'+x).classList.remove('active')});$('#'+id).classList.add('active');state.screen=id==='homeView'?'home':id==='wizardView'?'wizard':'tournament';save()}
function init(){bind();if(state.screen==='wizard')show('wizardView');else if(state.screen==='tournament'&&state.config)show('tournamentView');else show('homeView');$('#resumeBtn').disabled=!(state.config&&state.rotations&&state.rotations.length);if(state.screen==='wizard')renderWizard();if(state.screen==='tournament'&&state.config)renderTournament();timer=setInterval(tick,300);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(function(){})}
function bind(){
 $('#startWizardBtn').onclick=function(){state={screen:'wizard',step:1,draft:draft(),role:'teacher'};show('wizardView');renderWizard()};
 $('#resumeBtn').onclick=function(){if(state.config){show('tournamentView');renderTournament()}};
 $('#wizardHomeBtn').onclick=function(){show('homeView')};$('#prevStepBtn').onclick=prev;$('#nextStepBtn').onclick=next;
 $('#tournamentHomeBtn').onclick=function(){show('homeView')};$('#studentModeBtn').onclick=function(){state.role=state.role==='student'?'teacher':'student';save();renderTournament()};
 $('#tvModeBtn').onclick=openTv;$('#exitTvBtn').onclick=closeTv;
 $$('.nav-pill').forEach(function(b){b.onclick=function(){openTab(b.dataset.tab)}});
 $('#startAllBtn').onclick=startAll;$('#pauseAllBtn').onclick=pauseAll;$('#stopAllBtn').onclick=function(){if(confirm('Terminer tous les matchs en cours ?'))finishAll()};$('#nextRotationBtn').onclick=nextRotation;
 $('#whereSelect').onchange=renderWhere;$('#exportCsvBtn').onclick=exportCsv;$('#exportExcelBtn').onclick=exportExcel;$('#printBtn').onclick=function(){window.print()};$('#exportJsonBtn').onclick=exportJson;
}
function wrap(k,t,p,b){return'<div class="step-card"><p class="eyebrow">'+k+'</p><h2>'+t+'</h2><p class="step-intro">'+p+'</p>'+b+'</div>'}
function choice(cls,key,title,desc,sel,icon){return'<button type="button" class="choice-card '+(sel?'selected':'')+'" data-'+cls+'="'+esc(key)+'">'+(icon?'<span class="icon">'+icon+'</span>':'')+'<strong>'+esc(title)+'</strong>'+(desc?'<span>'+esc(desc)+'</span>':'')+'</button>'}
function renderWizard(){var d=state.draft,st=state.step,titles=['Sport','Format','Terrains','Équipes','Noms','Formule','Fin du match','Fonctionnement','Résumé'];$('#stepLabel').textContent='Étape '+st+' sur 9';$('#stepTitleMini').textContent=titles[st-1];$('#progressBar').style.width=(st/9*100)+'%';$('#prevStepBtn').style.visibility=st===1?'hidden':'visible';$('#nextStepBtn').textContent=st===9?'Créer le tournoi':'Continuer →';var h='';
 if(st===1){var x='';Object.keys(SPORTS).forEach(function(k){var s=SPORTS[k];x+=choice('sport',k,s[1],'',d.sport===k,s[0])});h=wrap('1. ACTIVITÉ','Quel sport ?','Une seule décision sur cet écran.','<div class="choice-grid">'+x+'</div>')}
 if(st===2){var sp=SPORTS[d.sport];if(sp[2].indexOf(d.format)<0)d.format=sp[2][0];var x2='';sp[2].forEach(function(f){x2+=choice('format',f,f,sp[1],d.format===f,'')});h=wrap('2. FORMAT',sp[0]+' '+sp[1]+' : quel format ?','Choisis la forme de pratique.','<div class="choice-grid">'+x2+'</div>')}
 if(st===3){var pv='';for(var i=1;i<=d.courts;i++)pv+='<div>Terrain '+i+'</div>';h=wrap('3. TERRAINS','Combien de terrains ?','Ils seront représentés exactement ainsi pendant le tournoi.','<div class="counter-card"><div class="counter"><button data-num="courts" data-d="-1">−</button><div><div class="counter-value">'+d.courts+'</div><div class="counter-label">terrain'+(d.courts>1?'s':'')+'</div></div><button data-num="courts" data-d="1">＋</button></div></div><div class="court-preview">'+pv+'</div>')}
 if(st===4)h=wrap('4. ÉQUIPES','Combien d’équipes ou de joueurs ?','En badminton simple, un joueur correspond à une équipe.','<div class="counter-card"><div class="counter"><button data-num="count" data-d="-1">−</button><div><div class="counter-value">'+d.count+'</div><div class="counter-label">équipe'+(d.count>1?'s':'')+' / joueur'+(d.count>1?'s':'')+'</div></div><button data-num="count" data-d="1">＋</button></div></div>')
 if(st===5){d.teams=teams(d.count,d.teams);var rows='';d.teams.forEach(function(t,i){rows+='<div class="team-row"><input class="dn-color" data-i="'+i+'" type="color" value="'+t.color+'"><input class="dn-name" data-i="'+i+'" value="'+esc(t.name)+'"><textarea class="dn-members" data-i="'+i+'" placeholder="Joueurs, un par ligne">'+esc((t.members||[]).join(String.fromCharCode(10)))+'</textarea></div>'});h=wrap('5. PARTICIPANTS','Qui participe ?','Renomme simplement les équipes ou joueurs.','<div class="teams-editor">'+rows+'</div><details class="import-panel"><summary>Coller une liste rapidement</summary><textarea id="pasteList" rows="5" placeholder="Bleus'+String.fromCharCode(10)+'Rouges'+String.fromCharCode(10)+'Verts"></textarea><button id="applyList" class="btn secondary" type="button">Utiliser cette liste</button></details>')}
 if(st===6){var f='';Object.keys(FORMULAS).forEach(function(k){f+=choice('formula',k,FORMULAS[k][0],FORMULAS[k][1],d.formula===k,'')});h=wrap('6. FORMULE','Quelle formule de tournoi ?','Choisis le principe général.','<div class="choice-grid">'+f+'</div>')}
 if(st===7){var m='';Object.keys(MODES).forEach(function(k){m+=choice('mode',k,MODES[k][0],MODES[k][1],d.mode===k,'')});h=wrap('7. FIN DU MATCH','Comment se termine un match ?','Temps, score cible, les deux, ou libre.','<div class="choice-grid">'+m+'</div>')}
 if(st===8){var fields='';if(d.mode==='time'||d.mode==='hybrid')fields+='<label>Durée en minutes<input id="dur" type="number" min="1" max="60" value="'+Math.round(d.duration/60)+'"></label>';if(d.mode==='score'||d.mode==='hybrid')fields+='<label>Score à atteindre<input id="target" type="number" min="1" max="100" value="'+d.target+'"></label>';var strat=choice('strategy','independent','Terrain par terrain','Chaque terrain démarre quand il est prêt.',d.strategy==='independent','')+choice('strategy','synchronized','Tous ensemble','L’enseignant lance tous les matchs prêts.',d.strategy==='synchronized','')+choice('strategy','first','Premier fini = arrêt général','Le premier match terminé arrête les autres.',d.strategy==='first','');h=wrap('8. FONCTIONNEMENT','Comment lancer les matchs ?','C’est ici que tu choisis terrain par terrain ou tous ensemble.','<div class="inline-grid">'+fields+'</div><div class="choice-grid">'+strat+'</div><div class="toggle-list"><label class="toggle-line"><input id="studentStart" type="checkbox" '+(d.studentStart?'checked':'')+'> Les élèves peuvent démarrer leur terrain</label><label class="toggle-line"><input id="studentScore" type="checkbox" '+(d.studentScore?'checked':'')+'> Les élèves peuvent saisir les scores</label><label class="toggle-line"><input id="sound" type="checkbox" '+(d.sound?'checked':'')+'> Signal sonore de fin</label><button id="testSound" class="btn ghost" type="button">🔊 Tester le son</button></div>')}
 if(st===9){var s9=SPORTS[d.sport];h=wrap('9. RÉSUMÉ','Le tournoi est prêt.','Un dernier contrôle avant de générer les rotations.','<div class="summary-box">'+sum('Sport',s9[0]+' '+s9[1])+sum('Format',d.format)+sum('Terrains',d.courts)+sum('Équipes / joueurs',d.count)+sum('Formule',FORMULAS[d.formula][0])+sum('Fin du match',MODES[d.mode][0])+sum('Démarrage',strategyName(d.strategy))+sum('Son',d.sound?'Activé':'Désactivé')+'</div>')}
 $('#wizardContent').innerHTML=h;bindStep();save()}
function sum(a,b){return'<div class="summary-chip"><span>'+esc(a)+'</span><strong>'+esc(b)+'</strong></div>'}
function bindStep(){
 $$('[data-sport]').forEach(function(b){b.onclick=function(){state.draft.sport=b.dataset.sport;state.draft.format=SPORTS[b.dataset.sport][2][0];state.draft.target=SPORTS[b.dataset.sport][3];renderWizard()}});$$('[data-format]').forEach(function(b){b.onclick=function(){state.draft.format=b.dataset.format;renderWizard()}});$$('[data-formula]').forEach(function(b){b.onclick=function(){state.draft.formula=b.dataset.formula;renderWizard()}});$$('[data-mode]').forEach(function(b){b.onclick=function(){state.draft.mode=b.dataset.mode;renderWizard()}});$$('[data-strategy]').forEach(function(b){b.onclick=function(){state.draft.strategy=b.dataset.strategy;renderWizard()}});
 $$('[data-num]').forEach(function(b){b.onclick=function(){var k=b.dataset.num,v=Number(b.dataset.d);if(k==='courts')state.draft.courts=Math.max(1,Math.min(24,state.draft.courts+v));else{state.draft.count=Math.max(2,Math.min(64,state.draft.count+v));state.draft.teams=teams(state.draft.count,state.draft.teams)}renderWizard()}});
 $$('.dn-name').forEach(function(i){i.oninput=function(){state.draft.teams[Number(i.dataset.i)].name=i.value;save()}});$$('.dn-color').forEach(function(i){i.oninput=function(){state.draft.teams[Number(i.dataset.i)].color=i.value;save()}});$$('.dn-members').forEach(function(i){i.oninput=function(){state.draft.teams[Number(i.dataset.i)].members=i.value.split(String.fromCharCode(10)).filter(Boolean);save()}});
 if($('#applyList'))$('#applyList').onclick=function(){var a=$('#pasteList').value.split(String.fromCharCode(10)).map(function(x){return x.trim()}).filter(Boolean);if(!a.length)return;a=a.slice(0,64);state.draft.count=a.length;state.draft.teams=a.map(function(n,i){return{id:'t'+(i+1),name:n,color:COLORS[i%COLORS.length],members:[]}});renderWizard()};
 if($('#dur'))$('#dur').oninput=function(){state.draft.duration=Math.max(60,Math.min(3600,Number(this.value||5)*60));save()};if($('#target'))$('#target').oninput=function(){state.draft.target=Math.max(1,Math.min(100,Number(this.value||11)));save()};
 if($('#studentStart'))$('#studentStart').onchange=function(){state.draft.studentStart=this.checked;save()};if($('#studentScore'))$('#studentScore').onchange=function(){state.draft.studentScore=this.checked;save()};if($('#sound'))$('#sound').onchange=function(){state.draft.sound=this.checked;save()};if($('#testSound'))$('#testSound').onclick=function(){beep(true)};
}
function prev(){if(state.step>1){state.step--;renderWizard();scrollTo(0,0)}}function next(){if(state.step<9){state.step++;renderWizard();scrollTo(0,0)}else createTournament()}
