(() => {
'use strict';
const SPORTS = {
  badminton:{name:'Badminton',icon:'🏸',formats:['Simple','Double'],defaultTarget:11},
  basketball:{name:'Basket-ball',icon:'🏀',formats:['3 contre 3','5 contre 5','Personnalisé'],defaultTarget:11},
  handball:{name:'Handball',icon:'🤾',formats:['4 contre 4','7 contre 7','Personnalisé'],defaultTarget:5},
  football:{name:'Football',icon:'⚽',formats:['5 contre 5','8 contre 8','11 contre 11','Futsal','Personnalisé'],defaultTarget:3},
  volleyball:{name:'Volley-ball',icon:'🏐',formats:['2 contre 2','4 contre 4','6 contre 6','Personnalisé'],defaultTarget:15},
  tabletennis:{name:'Tennis de table',icon:'🏓',formats:['Simple','Double'],defaultTarget:11},
  tennis:{name:'Tennis',icon:'🎾',formats:['Simple','Double'],defaultTarget:4},
  ultimate:{name:'Ultimate',icon:'🥏',formats:['5 contre 5','Personnalisé'],defaultTarget:7},
  rugby:{name:'Rugby',icon:'🏉',formats:['5 contre 5','7 contre 7','Personnalisé'],defaultTarget:5},
  hockey:{name:'Hockey',icon:'🏑',formats:['5 contre 5','Personnalisé'],defaultTarget:5},
  custom:{name:'Activité personnalisée',icon:'🏅',formats:['Format libre'],defaultTarget:10}
};
const COLORS=['#2563eb','#ef4444','#16a34a','#eab308','#7c3aed','#ea580c','#0891b2','#db2777','#334155','#84cc16','#0d9488','#8b5cf6','#f97316','#64748b','#14b8a6','#be123c'];
const FORMULA_HELP={roundrobin:'Chaque équipe rencontre toutes les autres. Les rencontres sont réparties automatiquement sur les terrains disponibles.',knockout:'Tableau à élimination directe. Les vainqueurs avancent automatiquement lorsque la rotation est terminée.',pools:'Deux poules équilibrées, puis phase finale avec les meilleures équipes.',ladder:'Montante-descendante : les vainqueurs progressent vers le terrain 1, les perdants descendent.',swiss:'Les équipes jouent un nombre limité de rondes contre des adversaires ayant des résultats proches.'};
const STORAGE_KEY='tournoi-eps-v1';
let audioCtx=null, ticker=null;
let state = loadState() || {role:'teacher',screen:'home',config:null,teams:[],rotations:[],currentRotation:0,phase:'setup',swissRound:0};

const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const els={home:$('#homeView'),setup:$('#setupView'),tournament:$('#tournamentView'),sport:$('#sportSelect'),format:$('#formatSelect'),teamCount:$('#teamCount'),courtCount:$('#courtCount'),teamsEditor:$('#teamsEditor'),formula:$('#formulaSelect'),formulaHelp:$('#formulaHelp'),duration:$('#durationMin'),target:$('#targetScore'),finish:$('#finishStrategy'),studentStart:$('#studentStart'),studentScore:$('#studentScore'),soundEnabled:$('#soundEnabled'),summary:$('#setupSummary'),courts:$('#courtsGrid'),rotationLabel:$('#rotationLabel'),rotationProgress:$('#rotationProgress'),globalClock:$('#globalClock'),resting:$('#restingTeams'),title:$('#tournamentTitle'),meta:$('#tournamentMeta'),standings:$('#standingsBody'),whereSelect:$('#whereSelect'),whereResult:$('#whereResult'),schedule:$('#scheduleList'),next:$('#nextRotationBtn'),resume:$('#resumeTournamentBtn')};

function init(){
  populateSports(); bind(); setRole(state.role||'teacher'); showScreen(state.screen||'home');
  if(state.config && state.rotations?.length){ els.resume.disabled=false; } else els.resume.disabled=true;
  if(state.screen==='tournament' && state.config) renderTournament();
  updateSetupUI();
  if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{});
  ticker=setInterval(tick,250);
}
function bind(){
  $('#newTournamentBtn').addEventListener('click',()=>startSetup());
  els.resume.addEventListener('click',()=>{if(state.config){state.screen='tournament';save();showScreen('tournament');renderTournament();}});
  $$('[data-go-home],#homeBtn').forEach(b=>b.addEventListener('click',()=>{state.screen='home';save();showScreen('home');}));
  $$('.role-btn').forEach(b=>b.addEventListener('click',()=>setRole(b.dataset.role)));
  $$('.quick-card').forEach(b=>b.addEventListener('click',()=>applyPreset(b.dataset.preset)));
  els.sport.addEventListener('change',()=>{populateFormats();els.target.value=SPORTS[els.sport.value].defaultTarget;updateSetupUI();});
  [els.format,els.teamCount,els.courtCount,els.formula,els.duration,els.target,els.finish,els.studentStart,els.studentScore,els.soundEnabled].forEach(x=>x.addEventListener('input',updateSetupUI));
  $$('input[name=endMode]').forEach(x=>x.addEventListener('change',updateSetupUI));
  $('#buildTeamsBtn').addEventListener('click',()=>buildTeamEditor(Number(els.teamCount.value)));
  $('#applyPasteBtn').addEventListener('click',()=>applyDelimited($('#pasteImport').value));
  $('#csvFile').addEventListener('change',readCsvFile);
  $('#testSoundBtn').addEventListener('click',()=>{initAudio();playSignal('finish');});
  $('#soundTestLive').addEventListener('click',()=>{initAudio();playSignal('finish');});
  $('#setupForm').addEventListener('submit',createTournament);
  $('#editTournamentBtn').addEventListener('click',()=>{hydrateSetupFromState();state.screen='setup';save();showScreen('setup');});
  $$('.tab').forEach(b=>b.addEventListener('click',()=>openTab(b.dataset.tab)));
  $('#startAllBtn').addEventListener('click',startAllReady);
  $('#pauseAllBtn').addEventListener('click',pauseAll);
  $('#stopAllBtn').addEventListener('click',()=>{if(confirm('Terminer tous les matchs en cours ?')) finishAll('manual');});
  $('#add30Btn').addEventListener('click',()=>addTimeAll(30));
  els.next.addEventListener('click',nextRotation);
  els.whereSelect.addEventListener('change',renderWhere);
  $('#exportCsvBtn').addEventListener('click',exportCsv);
  $('#exportExcelBtn').addEventListener('click',exportExcel);
  $('#printBtn').addEventListener('click',()=>window.print());
  $('#exportJsonBtn').addEventListener('click',exportJson);
}
function populateSports(){els.sport.innerHTML=Object.entries(SPORTS).map(([k,v])=>`<option value="${k}">${v.icon} ${v.name}</option>`).join('');populateFormats();}
function populateFormats(){const sport=SPORTS[els.sport.value]||SPORTS.badminton;els.format.innerHTML=sport.formats.map(f=>`<option>${f}</option>`).join('');}
function startSetup(){state.screen='setup';showScreen('setup');buildTeamEditor(Number(els.teamCount.value));updateSetupUI();}
function applyPreset(p){startSetup();const map={badminton:['badminton','Simple',18,9,'ladder','score',11,5],basket3:['basketball','3 contre 3',8,4,'roundrobin','hybrid',11,6],handball:['handball','7 contre 7',6,3,'roundrobin','time',5,6],tabletennis:['tabletennis','Simple',12,6,'roundrobin','score',11,5]};const v=map[p];if(!v)return;els.sport.value=v[0];populateFormats();els.format.value=v[1];els.teamCount.value=v[2];els.courtCount.value=v[3];els.formula.value=v[4];document.querySelector(`input[name=endMode][value=${v[5]}]`).checked=true;els.target.value=v[6];els.duration.value=v[7];buildTeamEditor(v[2]);updateSetupUI();}
function endMode(){return document.querySelector('input[name=endMode]:checked').value;}
function updateSetupUI(){const mode=endMode();$('#durationWrap').style.display=(mode==='time'||mode==='hybrid')?'grid':'none';$('#targetWrap').style.display=(mode==='score'||mode==='hybrid')?'grid':'none';els.formulaHelp.textContent=FORMULA_HELP[els.formula.value]||'';const n=clampInt(els.teamCount.value,2,64), c=clampInt(els.courtCount.value,1,24);const approx=Math.ceil((n*(n-1)/2)/c);els.summary.innerHTML=`<div class="summary-list"><div class="summary-item"><strong>${n}</strong><span>équipes / joueurs</span></div><div class="summary-item"><strong>${c}</strong><span>terrains</span></div><div class="summary-item"><strong>${approx}</strong><span>rotations max estimées</span></div><div class="summary-item"><strong>${labelEndMode(mode)}</strong><span>fin des matchs</span></div></div>`;}
function buildTeamEditor(count,existing){count=clampInt(count,2,64);const old=existing||readTeamsEditor();els.teamsEditor.innerHTML='';for(let i=0;i<count;i++){const t=old[i]||{name:`Équipe ${i+1}`,color:COLORS[i%COLORS.length],members:[]};const div=document.createElement('div');div.className='team-edit';div.innerHTML=`<input class="team-color" type="color" value="${safeColor(t.color)}" aria-label="Couleur équipe ${i+1}"><input class="team-name-input" value="${escapeAttr(t.name)}" maxlength="40" aria-label="Nom équipe ${i+1}"><textarea class="team-members" placeholder="Prénoms / joueurs, un par ligne">${escapeHtml((t.members||[]).join('\n'))}</textarea>`;els.teamsEditor.appendChild(div);}}
function readTeamsEditor(){return $$('.team-edit').map((d,i)=>({id:`t${i+1}`,name:d.querySelector('.team-name-input').value.trim()||`Équipe ${i+1}`,color:d.querySelector('.team-color').value,members:d.querySelector('.team-members').value.split(/\n+/).map(s=>s.trim()).filter(Boolean)}));}
function applyDelimited(text){if(!text.trim())return toast('Collez d’abord une liste.');const lines=text.trim().split(/\r?\n/).filter(Boolean);const delim=lines[0].includes(';')?';':lines[0].includes('\t')?'\t':',';let rows=lines.map(l=>l.split(delim).map(v=>v.trim()));const header=rows[0].map(x=>x.toLowerCase());const hasHeader=header.some(x=>/nom|prénom|prenom|classe|équipe|equipe/.test(x));if(hasHeader)rows=rows.slice(1);let groups=new Map();rows.forEach((r,idx)=>{const team=hasHeader?(r[header.findIndex(x=>/équipe|equipe/.test(x))]||`Équipe ${idx+1}`):(r[3]||`Équipe ${idx+1}`);const person=hasHeader?[r[header.findIndex(x=>/prénom|prenom/.test(x))],r[header.findIndex(x=>x==='nom')]].filter(Boolean).join(' ')||r[0]:[r[1],r[0]].filter(Boolean).join(' ')||r[0];if(!groups.has(team))groups.set(team,[]);groups.get(team).push(person);});const teams=Array.from(groups.entries()).map(([name,members],i)=>({name,color:COLORS[i%COLORS.length],members}));els.teamCount.value=teams.length;buildTeamEditor(teams.length,teams);updateSetupUI();toast(`${rows.length} participant(s) importé(s).`);}
function readCsvFile(e){const f=e.target.files?.[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{$('#pasteImport').value=String(reader.result||'');applyDelimited(String(reader.result||''));};reader.readAsText(f);}
function createTournament(e){e.preventDefault();initAudio();let teams=readTeamsEditor();if(teams.length!==Number(els.teamCount.value)){buildTeamEditor(Number(els.teamCount.value),teams);teams=readTeamsEditor();}teams=teams.map((t,i)=>({...t,id:`t${i+1}`}));const cfg={name:$('#tournamentName').value.trim()||'Tournoi EPS',sport:els.sport.value,format:els.format.value,formula:els.formula.value,courts:clampInt(els.courtCount.value,1,24),endMode:endMode(),durationSec:clampInt(els.duration.value,1,60)*60,target:clampInt(els.target.value,1,100),finishStrategy:els.finish.value,studentStart:els.studentStart.checked,studentScore:els.studentScore.checked,soundEnabled:els.soundEnabled.checked};state={...state,screen:'tournament',role:'teacher',config:cfg,teams,rotations:[],currentRotation:0,phase:'main',swissRound:0};state.rotations=generateInitialRotations();save();showScreen('tournament');setRole('teacher');renderTournament();toast('Tournoi généré.');}
function generateInitialRotations(){switch(state.config.formula){case'knockout':return knockoutInitial();case'pools':return poolsInitial();case'ladder':return ladderRotation(state.teams.map(t=>t.id),1);case'swiss':state.swissRound=1;return swissRotation(1);default:return roundRobinRotations(state.teams.map(t=>t.id));}}
function roundRobinPairs(ids){const arr=[...ids];if(arr.length%2)arr.push(null);const n=arr.length,out=[];for(let r=0;r<n-1;r++){const pairs=[];for(let i=0;i<n/2;i++){const a=arr[i],b=arr[n-1-i];if(a&&b)pairs.push([a,b]);}out.push(pairs);arr.splice(1,0,arr.pop());}return out;}
function roundRobinRotations(ids,labelPrefix='Ronde'){const rounds=roundRobinPairs(ids),out=[];let rot=1;rounds.forEach((pairs,ri)=>chunk(pairs,state.config.courts).forEach(group=>out.push(makeRotation(group,rot++,`${labelPrefix} ${ri+1}`))));return out;}
function makeRotation(pairs,index,label,meta={}){return {id:`r${Date.now()}-${index}-${Math.random().toString(36).slice(2,6)}`,label:label||`Rotation ${index}`,meta,matches:pairs.map((p,i)=>newMatch(p[0],p[1],i+1))};}
function newMatch(a,b,court){return{id:`m-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,court,teamAId:a,teamBId:b,scoreA:0,scoreB:0,status:'waiting',remainingSec:state.config.durationSec,endAt:null,winnerId:null,reason:null};}
function knockoutInitial(){const ids=[...state.teams.map(t=>t.id)],pairs=[];state._knockoutByes={};for(let i=0;i<ids.length;i+=2){if(ids[i+1])pairs.push([ids[i],ids[i+1]]);else state._knockoutByes[1]=[ids[i]];}return chunk(pairs,state.config.courts).map((g,i)=>makeRotation(g,i+1,'Élimination — tour 1',{knockoutRound:1}));}
function poolsInitial(){const a=[],b=[];state.teams.forEach((t,i)=>(i%2?a:b).push(t.id));const ra=roundRobinRotations(a,'Poule A'),rb=roundRobinRotations(b,'Poule B');const max=Math.max(ra.length,rb.length),out=[];for(let i=0;i<max;i++){const pairs=[];if(ra[i])pairs.push(...ra[i].matches.map(m=>[m.teamAId,m.teamBId]));if(rb[i])pairs.push(...rb[i].matches.map(m=>[m.teamAId,m.teamBId]));chunk(pairs,state.config.courts).forEach((g,j)=>out.push(makeRotation(g,out.length+1,`Poules ${i+1}.${j+1}`,{poolStage:true})));}return out;}
function ladderRotation(order,num){const pairs=[];for(let i=0;i<Math.min(order.length,state.config.courts*2);i+=2)if(order[i+1])pairs.push([order[i],order[i+1]]);return[makeRotation(pairs,num,`Montante-descendante ${num}`,{ladderOrder:order})];}
function swissRotation(round){const standings=getStandings();const sorted=(round===1?[...state.teams.map(t=>t.id)]:standings.map(s=>s.id));const pairs=[],used=new Set(),history=new Set(allMatches().filter(m=>m.status==='finished').map(m=>[m.teamAId,m.teamBId].sort().join('|')));for(let i=0;i<sorted.length;i++){const a=sorted[i];if(used.has(a))continue;let b=null;for(let j=i+1;j<sorted.length;j++){const cand=sorted[j];if(used.has(cand))continue;if(!history.has([a,cand].sort().join('|'))){b=cand;break;}}if(!b)b=sorted.find(x=>x!==a&&!used.has(x))||null;if(b){used.add(a);used.add(b);pairs.push([a,b]);}}return chunk(pairs,state.config.courts).map((g,i)=>makeRotation(g,i+1,`Suisse ${round}.${i+1}`,{swissRound:round}));}
function currentRotation(){return state.rotations[state.currentRotation]||null;}
function allMatches(){return state.rotations.flatMap(r=>r.matches||[]);}
function showScreen(name){['home','setup','tournament'].forEach(n=>els[n].classList.toggle('active',n===name));if(name==='tournament')renderTournament();}
function setRole(role){state.role=role;document.body.classList.toggle('student-mode',role==='student');document.body.classList.toggle('tv-mode',role==='tv');$$('.role-btn').forEach(b=>b.classList.toggle('active',b.dataset.role===role));if(role==='tv'){state.screen='tournament';showScreen('tournament');openTab('courts');}save();if(state.config)renderCourts();}
function renderTournament(){if(!state.config)return;els.title.textContent=state.config.name;const sp=SPORTS[state.config.sport];els.meta.textContent=`${sp?.icon||'🏅'} ${sp?.name||'Sport'} • ${state.config.format} • ${state.config.courts} terrain(s)`;renderCourts();renderStandings();renderSchedule();renderWhereOptions();}
function renderCourts(){const rot=currentRotation();if(!rot){els.courts.innerHTML='<div class="panel">Tournoi terminé.</div>';els.next.disabled=true;return;}els.rotationLabel.textContent=`${state.currentRotation+1} / ${state.rotations.length}`;const finished=rot.matches.filter(m=>m.status==='finished').length;els.rotationProgress.textContent=`${finished} / ${rot.matches.length} matchs terminés`;const maxCourt=state.config.courts;let html='';for(let c=1;c<=maxCourt;c++){const m=rot.matches.find(x=>x.court===c);html+=m?courtCard(m):`<article class="court-card"><div class="court-head"><strong>Terrain ${c}</strong><span class="status">LIBRE</span></div><div class="empty-court">Aucun match sur cette rotation</div></article>`;}els.courts.innerHTML=html;bindCourtActions();const playing=new Set(rot.matches.flatMap(m=>[m.teamAId,m.teamBId]));const rest=state.teams.filter(t=>!playing.has(t.id));els.resting.innerHTML=rest.length?`<strong>Au repos :</strong> ${rest.map(t=>escapeHtml(t.name)).join(' • ')}`:'<strong>Toutes les équipes jouent.</strong>';els.next.disabled=!rot.matches.every(m=>m.status==='finished');renderGlobalClock();}
function courtCard(m){const a=team(m.teamAId),b=team(m.teamBId);const statusLabel={waiting:'PRÊT',running:'EN COURS',paused:'PAUSE',finished:'TERMINÉ'}[m.status]||m.status;const allowScore=state.role==='teacher'||(state.role==='student'&&state.config.studentScore);const allowStart=state.role==='teacher'||(state.role==='student'&&state.config.studentStart);return `<article class="court-card ${m.status}" data-match="${m.id}"><div class="court-head"><strong>Terrain ${m.court}</strong><span class="status">${statusLabel}</span></div><div class="matchup"><div class="team-side"><div class="team-dot" style="background:${a.color}"></div><div class="team-name">${escapeHtml(a.name)}</div><div class="score">${m.scoreA}</div>${allowScore?scoreButtons(m.id,'A'):''}</div><div class="versus">VS</div><div class="team-side"><div class="team-dot" style="background:${b.color}"></div><div class="team-name">${escapeHtml(b.name)}</div><div class="score">${m.scoreB}</div>${allowScore?scoreButtons(m.id,'B'):''}</div></div>${state.config.endMode!=='score'&&state.config.endMode!=='free'?`<div class="court-clock">${formatTime(m.remainingSec)}</div>`:''}<div class="court-actions">${allowStart&&m.status==='waiting'?`<button class="btn primary match-start" data-id="${m.id}">▶ Démarrer</button>`:''}${allowStart&&m.status==='running'?`<button class="btn secondary match-pause" data-id="${m.id}">⏸ Pause</button>`:''}${allowStart&&m.status==='paused'?`<button class="btn primary match-start" data-id="${m.id}">▶ Reprendre</button>`:''}${(state.role==='teacher'||allowStart)&&m.status!=='finished'?`<button class="btn ghost match-finish" data-id="${m.id}">Terminer</button>`:`<button class="btn ghost match-reopen teacher-only" data-id="${m.id}">Modifier</button>`}</div></article>`;}
function scoreButtons(id,side){return `<div class="score-controls"><button class="score-btn" data-score="-1" data-side="${side}" data-id="${id}">−</button><button class="score-btn" data-score="1" data-side="${side}" data-id="${id}">＋</button></div>`;}
function bindCourtActions(){$$('.score-btn').forEach(b=>b.addEventListener('click',()=>changeScore(b.dataset.id,b.dataset.side,Number(b.dataset.score))));$$('.match-start').forEach(b=>b.addEventListener('click',()=>startMatch(b.dataset.id)));$$('.match-pause').forEach(b=>b.addEventListener('click',()=>pauseMatch(b.dataset.id)));$$('.match-finish').forEach(b=>b.addEventListener('click',()=>finishMatch(findMatch(b.dataset.id),'manual')));$$('.match-reopen').forEach(b=>b.addEventListener('click',()=>reopenMatch(b.dataset.id)));}
function startMatch(id){initAudio();const m=findMatch(id);if(!m||m.status==='finished')return;if(m.status==='paused'||m.status==='waiting'){m.status='running';if(state.config.endMode==='time'||state.config.endMode==='hybrid')m.endAt=Date.now()+m.remainingSec*1000;save();renderCourts();}}
function pauseMatch(id){const m=findMatch(id);if(!m||m.status!=='running')return;syncRemaining(m);m.status='paused';m.endAt=null;save();renderCourts();}
function startAllReady(){initAudio();const rot=currentRotation();if(!rot)return;rot.matches.forEach(m=>{if(m.status==='waiting'||m.status==='paused'){m.status='running';if(state.config.endMode==='time'||state.config.endMode==='hybrid')m.endAt=Date.now()+m.remainingSec*1000;}});playSignal('start');save();renderCourts();}
function pauseAll(){const rot=currentRotation();if(!rot)return;rot.matches.forEach(m=>{if(m.status==='running'){syncRemaining(m);m.status='paused';m.endAt=null;}});save();renderCourts();}
function addTimeAll(sec){const rot=currentRotation();if(!rot)return;rot.matches.forEach(m=>{if(m.status!=='finished'){m.remainingSec+=sec;if(m.status==='running'&&m.endAt)m.endAt+=sec*1000;}});save();renderCourts();toast(`+${sec} secondes ajoutées.`);}
function finishAll(reason){const rot=currentRotation();if(!rot)return;rot.matches.forEach(m=>{if(m.status!=='finished')finishMatch(m,reason,true);});if(state.config.soundEnabled)playSignal('finish');save();renderTournament();}
function changeScore(id,side,delta){const m=findMatch(id);if(!m)return;if(m.status==='waiting'&&state.config.endMode!=='free')startMatch(id);if(side==='A')m.scoreA=Math.max(0,m.scoreA+delta);else m.scoreB=Math.max(0,m.scoreB+delta);if((state.config.endMode==='score'||state.config.endMode==='hybrid')&&(m.scoreA>=state.config.target||m.scoreB>=state.config.target)){finishMatch(m,'target');return;}save();renderTournament();}
function finishMatch(m,reason,silent=false){if(!m)return;syncRemaining(m);m.status='finished';m.endAt=null;m.reason=reason;m.winnerId=m.scoreA===m.scoreB?null:(m.scoreA>m.scoreB?m.teamAId:m.teamBId);if(!silent&&state.config.soundEnabled)playSignal('finish');if(state.config.finishStrategy==='firstEndsAll'&&!silent){finishAll('first-match');return;}save();renderTournament();}
function reopenMatch(id){const m=findMatch(id);if(!m)return;m.status='paused';m.winnerId=null;m.reason=null;if(m.remainingSec<=0)m.remainingSec=state.config.durationSec;save();renderTournament();}
function syncRemaining(m){if(m.status==='running'&&m.endAt)m.remainingSec=Math.max(0,Math.ceil((m.endAt-Date.now())/1000));}
function tick(){if(!state.config||state.screen!=='tournament')return;let changed=false;const rot=currentRotation();if(!rot)return;rot.matches.forEach(m=>{if(m.status==='running'&&(state.config.endMode==='time'||state.config.endMode==='hybrid')){const before=m.remainingSec;syncRemaining(m);if(m.remainingSec!==before)changed=true;if(m.remainingSec<=0){finishMatch(m,'time',true);changed=true;}}});if(changed){const anyJustZero=rot.matches.some(m=>m.status==='finished'&&m.reason==='time'&&m.remainingSec===0);if(anyJustZero&&state.config.soundEnabled&&!rot._timeSounded){rot._timeSounded=true;playSignal('finish');}save();renderCourts();renderStandings();}}
function renderGlobalClock(){const rot=currentRotation();if(!rot){els.globalClock.textContent='—';return;}const running=rot.matches.filter(m=>m.status==='running');if(!running.length){const remaining=rot.matches.filter(m=>m.status!=='finished').map(m=>m.remainingSec);els.globalClock.textContent=remaining.length&&state.config.endMode!=='score'&&state.config.endMode!=='free'?formatTime(Math.max(...remaining)):'—';return;}if(state.config.finishStrategy==='synchronized'){els.globalClock.textContent=formatTime(Math.max(...running.map(m=>m.remainingSec)));}else if(state.config.endMode==='score'||state.config.endMode==='free'){els.globalClock.textContent=`${running.length} en cours`;}else els.globalClock.textContent=`${running.length} ▶`;}
function nextRotation(){const rot=currentRotation();if(!rot||!rot.matches.every(m=>m.status==='finished'))return toast('Termine d’abord les matchs de la rotation.');const formula=state.config.formula;if(formula==='knockout'&&state.currentRotation===state.rotations.length-1){advanceKnockout();}else if(formula==='pools'&&state.currentRotation===state.rotations.length-1){if(!state._poolsFinalsAdded)addPoolFinals();else if(rot.meta?.finalStage==='semi')addPoolMedalMatches(rot); }else if(formula==='ladder'){addNextLadder();}else if(formula==='swiss'&&state.currentRotation===state.rotations.length-1&&state.swissRound<Math.ceil(Math.log2(state.teams.length))+1){state.swissRound++;state.rotations.push(...swissRotation(state.swissRound));}if(state.currentRotation<state.rotations.length-1)state.currentRotation++;else{toast('Tournoi terminé. Classement final disponible.');}save();renderTournament();}
function advanceKnockout(){const lastRound=state.rotations.filter(r=>r.meta?.knockoutRound).reduce((m,r)=>Math.max(m,r.meta.knockoutRound||0),1);const roundRots=state.rotations.filter(r=>r.meta?.knockoutRound===lastRound);if(!roundRots.every(r=>r.matches.every(m=>m.status==='finished')))return;const winners=[...roundRots.flatMap(r=>r.matches).map(m=>m.winnerId||tieWinner(m)).filter(Boolean),...((state._knockoutByes||{})[lastRound]||[])];if(winners.length<=1)return;const nextRound=lastRound+1,pairs=[];state._knockoutByes=state._knockoutByes||{};state._knockoutByes[nextRound]=[];for(let i=0;i<winners.length;i+=2){if(winners[i+1])pairs.push([winners[i],winners[i+1]]);else state._knockoutByes[nextRound].push(winners[i]);}chunk(pairs,state.config.courts).forEach(g=>state.rotations.push(makeRotation(g,state.rotations.length+1,`Élimination — tour ${nextRound}`,{knockoutRound:nextRound})));}
function addPoolFinals(){const s=getStandings();const a=state.teams.filter((t,i)=>i%2===0).map(t=>t.id),b=state.teams.filter((t,i)=>i%2===1).map(t=>t.id);const sa=s.filter(x=>a.includes(x.id)),sb=s.filter(x=>b.includes(x.id));if(sa[0]&&sb[1]&&sb[0]&&sa[1]){state.rotations.push(makeRotation([[sa[0].id,sb[1].id],[sb[0].id,sa[1].id]],state.rotations.length+1,'Demi-finales',{finalStage:'semi'}));state._poolsFinalsAdded=true;}else toast('Pas assez d’équipes pour la phase finale.');}
function addPoolMedalMatches(semiRot){const ms=semiRot.matches;if(ms.length<2)return;const winners=ms.map(m=>m.winnerId||tieWinner(m)),losers=ms.map(m=>m.winnerId===m.teamAId?m.teamBId:m.teamAId);state.rotations.push(makeRotation([[winners[0],winners[1]],[losers[0],losers[1]]],state.rotations.length+1,'Finale et petite finale',{finalStage:'final'}));}
function addNextLadder(){const rot=currentRotation();let order=[...(rot.meta?.ladderOrder||state.teams.map(t=>t.id))];rot.matches.forEach((m,idx)=>{const pos=idx*2;if(m.winnerId===order[pos+1]){const tmp=order[pos];order[pos]=order[pos+1];order[pos+1]=tmp;}});state.rotations.push(...ladderRotation(order,state.rotations.length+1));}
function tieWinner(m){return m.scoreA>=m.scoreB?m.teamAId:m.teamBId;}
function getStandings(){const rows=state.teams.map(t=>({id:t.id,name:t.name,color:t.color,p:0,w:0,d:0,l:0,for:0,against:0,pts:0}));const map=new Map(rows.map(r=>[r.id,r]));allMatches().filter(m=>m.status==='finished').forEach(m=>{const a=map.get(m.teamAId),b=map.get(m.teamBId);if(!a||!b)return;a.p++;b.p++;a.for+=m.scoreA;a.against+=m.scoreB;b.for+=m.scoreB;b.against+=m.scoreA;if(m.scoreA===m.scoreB){a.d++;b.d++;a.pts++;b.pts++;}else if(m.scoreA>m.scoreB){a.w++;b.l++;a.pts+=3;}else{b.w++;a.l++;b.pts+=3;}});return rows.map(r=>({...r,diff:r.for-r.against})).sort((x,y)=>y.pts-x.pts||y.diff-x.diff||y.for-x.for||x.name.localeCompare(y.name,'fr'));}
function renderStandings(){if(!state.config)return;els.standings.innerHTML=getStandings().map((r,i)=>`<tr><td>${i+1}</td><td><span class="rank-team"><span class="rank-dot" style="background:${r.color}"></span>${escapeHtml(r.name)}</span></td><td>${r.p}</td><td>${r.w}</td><td>${r.d}</td><td>${r.l}</td><td>${r.for}</td><td>${r.against}</td><td>${r.diff}</td><td><strong>${r.pts}</strong></td></tr>`).join('');}
function renderSchedule(){if(!state.config)return;els.schedule.innerHTML=state.rotations.map((r,i)=>`<section class="schedule-round"><h4>${i+1}. ${escapeHtml(r.label)}</h4><div class="schedule-matches">${r.matches.map(m=>`<div class="schedule-match"><strong>Terrain ${m.court}</strong><br>${escapeHtml(team(m.teamAId).name)} — ${escapeHtml(team(m.teamBId).name)}${m.status==='finished'?`<br><b>${m.scoreA} – ${m.scoreB}</b>`:''}</div>`).join('')}</div></section>`).join('');}
function renderWhereOptions(){if(!state.config)return;const prev=els.whereSelect.value;els.whereSelect.innerHTML=state.teams.map(t=>`<option value="${t.id}">${escapeHtml(t.name)}</option>`).join('');if(prev&&state.teams.some(t=>t.id===prev))els.whereSelect.value=prev;renderWhere();}
function renderWhere(){if(!state.config)return;const id=els.whereSelect.value,rot=currentRotation();const now=rot?.matches.find(m=>m.teamAId===id||m.teamBId===id);if(now){const opp=team(now.teamAId===id?now.teamBId:now.teamAId);els.whereResult.innerHTML=`<div class="big-result">Terrain ${now.court}</div><p>Maintenant contre <strong>${escapeHtml(opp.name)}</strong> • ${statusHuman(now.status)}</p>`;return;}for(let i=state.currentRotation+1;i<state.rotations.length;i++){const m=state.rotations[i].matches.find(x=>x.teamAId===id||x.teamBId===id);if(m){const opp=team(m.teamAId===id?m.teamBId:m.teamAId);els.whereResult.innerHTML=`<div class="big-result">Tu es au repos</div><p>Prochain match : <strong>Terrain ${m.court}</strong> contre <strong>${escapeHtml(opp.name)}</strong> • rotation ${i+1}</p>`;return;}}els.whereResult.innerHTML='<div class="big-result">Pas de match à venir</div><p>Consulte le classement ou attends la prochaine génération de rencontres.</p>';}
function openTab(tab){$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$$('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===`${tab}Tab`));if(tab==='standings')renderStandings();if(tab==='schedule')renderSchedule();if(tab==='where')renderWhere();}
function exportCsv(){const s=getStandings();const lines=[['Rang','Équipe','J','V','N','D','Pour','Contre','Diff','Pts'],...s.map((r,i)=>[i+1,r.name,r.p,r.w,r.d,r.l,r.for,r.against,r.diff,r.pts])];download(`${slug(state.config.name)}-classement.csv`,lines.map(r=>r.map(csvCell).join(';')).join('\n'),'text/csv;charset=utf-8');}
function exportExcel(){const s=getStandings();const rows=s.map((r,i)=>`<tr><td>${i+1}</td><td style="background:${r.color};color:#fff;font-weight:bold">${escapeHtml(r.name)}</td><td>${r.p}</td><td>${r.w}</td><td>${r.d}</td><td>${r.l}</td><td>${r.for}</td><td>${r.against}</td><td>${r.diff}</td><td>${r.pts}</td></tr>`).join('');const html=`<html><head><meta charset="UTF-8"></head><body><h1>${escapeHtml(state.config.name)}</h1><table border="1"><tr><th>Rang</th><th>Équipe</th><th>J</th><th>V</th><th>N</th><th>D</th><th>Pour</th><th>Contre</th><th>Diff</th><th>Pts</th></tr>${rows}</table></body></html>`;download(`${slug(state.config.name)}-classement.xls`,html,'application/vnd.ms-excel');}
function exportJson(){download(`${slug(state.config.name)}-sauvegarde.json`,JSON.stringify(state,null,2),'application/json');}
function hydrateSetupFromState(){if(!state.config)return;$('#tournamentName').value=state.config.name;els.sport.value=state.config.sport;populateFormats();els.format.value=state.config.format;els.teamCount.value=state.teams.length;els.courtCount.value=state.config.courts;els.formula.value=state.config.formula;document.querySelector(`input[name=endMode][value=${state.config.endMode}]`).checked=true;els.duration.value=Math.max(1,Math.round(state.config.durationSec/60));els.target.value=state.config.target;els.finish.value=state.config.finishStrategy;els.studentStart.checked=state.config.studentStart;els.studentScore.checked=state.config.studentScore;els.soundEnabled.checked=state.config.soundEnabled;buildTeamEditor(state.teams.length,state.teams);updateSetupUI();}
function initAudio(){if(!audioCtx)try{audioCtx=new (window.AudioContext||window.webkitAudioContext)();}catch(e){}if(audioCtx?.state==='suspended')audioCtx.resume().catch(()=>{});}
function playSignal(kind){if(!state.config?.soundEnabled && state.config)return;initAudio();if(!audioCtx)return;const tones=kind==='start'?[660,880]:[440,330,220];tones.forEach((freq,i)=>{const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type='sine';osc.frequency.value=freq;gain.gain.setValueAtTime(.0001,audioCtx.currentTime+i*.16);gain.gain.exponentialRampToValueAtTime(.25,audioCtx.currentTime+i*.16+.01);gain.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+i*.16+.13);osc.connect(gain).connect(audioCtx.destination);osc.start(audioCtx.currentTime+i*.16);osc.stop(audioCtx.currentTime+i*.16+.14);});}
function team(id){return state.teams.find(t=>t.id===id)||{name:'—',color:'#94a3b8'};}
function findMatch(id){return allMatches().find(m=>m.id===id);}
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}catch(e){}}
function loadState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');}catch(e){return null;}}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>t.classList.remove('show'),2200);}
function download(name,content,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function chunk(arr,n){const out=[];for(let i=0;i<arr.length;i+=n)out.push(arr.slice(i,i+n));return out;}
function clampInt(v,min,max){v=parseInt(v,10);return Number.isFinite(v)?Math.min(max,Math.max(min,v)):min;}
function formatTime(sec){sec=Math.max(0,Math.round(sec||0));return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;}
function labelEndMode(m){return({time:'Temps',score:'Score',hybrid:'Score ou temps',free:'Libre'})[m]||m;}
function statusHuman(s){return({waiting:'prêt à démarrer',running:'en cours',paused:'en pause',finished:'terminé'})[s]||s;}
function escapeHtml(s){return String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}
function escapeAttr(s){return escapeHtml(s).replace(/'/g,'&#39;');}
function safeColor(c){return /^#[0-9a-f]{6}$/i.test(c||'')?c:'#2563eb';}
function csvCell(v){const s=String(v??'');return /[;"\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s;}
function slug(s){return String(s||'tournoi').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
init();
})();
